name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Requirements
      run: sudo apt-get install -y libdbus-1-dev pkg-config mingw-w64 && rustup target add x86_64-unknown-linux-gnu && rustup target add x86_64-pc-windows-gnu

    - name: Build Linux
      run: cargo build --target x86_64-unknown-linux-gnu --release --verbose -j 4
    - name: Build Windows
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose -j 3

    - name: Archive Executables
      run: zip -j linux_x86-64.zip target/x86_64-unknown-linux-gnu/release/beat_extractor && zip -j windows_x86-64.zip target/x86_64-pc-windows-gnu/release/beat_extractor.exe && zip -r windows_x86-64.zip icons
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "linux_x86-64.zip,windows_x86-64.zip"
        body: "Nightly build"
