name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      uses: skx/github-action-build@master
      with:
        builder: .github/build.sh
    - name: github-action-publish-binaries
      # You may pin to the exact commit or the version.
      # uses: skx/github-action-publish-binaries@b9ca5643b2f1d7371a6cba7f35333f1461bbc703
      uses: skx/github-action-publish-binaries@release-2.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The pattern of files to upload
        args:
          linux.zip
          windows.zip
              
